// List of all claimed domains from claim-all-domains.js
const CLAIMED_DOMAINS = [
    // CORE BRAND (.pulse)
    { name: 'chain', tld: 'pulse' },
    { name: 'digital', tld: 'pulse' },
    { name: 'feelthe', tld: 'pulse' },
    { name: 'web3', tld: 'pulse' },
    { name: 'dao', tld: 'pulse' },
    { name: 'ai', tld: 'pulse' },
    { name: 'dex', tld: 'pulse' },
    { name: 'marketplace', tld: 'pulse' },
    { name: 'social', tld: 'pulse' },
    { name: 'club', tld: 'pulse' },
    { name: 'mypulse', tld: 'pulse' },
    { name: 'bridge', tld: 'pulse' },
    { name: 'swap', tld: 'pulse' },
    { name: 'stake', tld: 'pulse' },
    { name: 'dev', tld: 'pulse' },
    { name: 'docs', tld: 'pulse' },
    
    // METAVERSE/COMMUNITY (.verse)
    { name: 'web3', tld: 'verse' },
    { name: 'dao', tld: 'verse' },
    { name: 'pulse', tld: 'verse' },
    { name: 'pulsemates', tld: 'verse' },
    { name: 'ai', tld: 'verse' },
    { name: 'dex', tld: 'verse' },
    { name: 'community', tld: 'verse' },
    { name: 'social', tld: 'verse' },
    { name: 'trade', tld: 'verse' },
    
    // CHAIN PULSE BRANDED (.cp)
    { name: 'digitalpulse', tld: 'cp' },
    { name: 'feelthepulse', tld: 'cp' },
    { name: 'defi', tld: 'cp' },
    { name: 'pulsemates', tld: 'cp' },
    { name: 'pulsewallet', tld: 'cp' },
    { name: 'pulseverse', tld: 'cp' },
    { name: 'creatorsally', tld: 'cp' },
    { name: 'wallet', tld: 'cp' },
    { name: 'pulsetoken', tld: 'cp' },
    { name: 'pulse', tld: 'cp' },
    { name: 'chainpulse', tld: 'cp' },
    { name: 'chainpulsedex', tld: 'cp' },
    { name: 'pulseai', tld: 'cp' },
    { name: 'dex', tld: 'cp' },
    { name: 'farm', tld: 'cp' },
    { name: 'api', tld: 'cp' },
    { name: 'market', tld: 'cp' },
    { name: 'nft', tld: 'cp' },
    { name: 'chat', tld: 'cp' },
    { name: 'twodonkeys', tld: 'cp' },
    { name: 'meowgangsters', tld: 'cp' },
    
    // PULSE VERSE (.pv)
    { name: 'digitalpulse', tld: 'pv' },
    { name: 'feelthepulse', tld: 'pv' },
    { name: 'defi', tld: 'pv' },
    { name: 'pulsemates', tld: 'pv' },
    { name: 'pulsewallet', tld: 'pv' },
    { name: 'pulseverse', tld: 'pv' },
    { name: 'creatorsally', tld: 'pv' },
    { name: 'wallet', tld: 'pv' },
    { name: 'pulsetoken', tld: 'pv' },
    { name: 'pulse', tld: 'pv' },
    { name: 'chainpulse', tld: 'pv' },
    { name: 'chainpulsedex', tld: 'pv' },
    { name: 'pulseai', tld: 'pv' },
    { name: 'dex', tld: 'pv' },
    { name: 'pool', tld: 'pv' },
    { name: 'sdk', tld: 'pv' },
    { name: 'nft', tld: 'pv' },
    { name: 'forum', tld: 'pv' },
    { name: 'twodonkeys', tld: 'pv' },
    { name: 'meowgangsters', tld: 'pv' }
];
